### ISSUE TITLE
running smart-broadcasting script

### ISSUE THREAD

**Issue by kangyang73** [Networks-Learning/tpprl#1]
@harrymvr I can't run the script "train-teaching.py", because there isn't the file "twitter_data.dill". Can you provide me a sample data about the file "twitter_data.dill"?
Thanks a lot!

**Comment by musically-ut** [comment]
Unfortunately, we cannot release the Twitter datasets. 

However, `twitter_data.dill` file just contains a `list` of `dict` with the following keys:

```python
[ ...,
{'duration': <duration-of-user-activity>, # scaled using `scaled_period` key
 'followees': {followee_id_1, followee_id_2, ...},
 'num_followees': <number_of_followees>,
 'num_other_posts': <number_of_posts_followees_saw>,
 'num_own_posts': <number_of_posts_this_user_made>,
 'num_user_events': <number_of_posts_this_user_made>,   # duplicated, legacy
 'scaled_period': 10000.0,  # maximum timestamp
 'seed': <random_seed>,  # used if sim_opts has stochastic broadcasters
 'sim_opts': <redqueen.opt_model.SimOpts object at ...>, # See note below
 'thres': None,  # legacy, unused
 'user_event_times': [8830.066457, 8830.066, ...], # Tweet times of user, scaled
 'user_id': 1, # Should be the same as `sim_opts.src_id`
},
...]
```

The `sim_opts` object contains _simulation options_ detailed in the `README.md` of [RedQueen](https://github.com/Networks-Learning/RedQueen). The options include the `followee-follower` social network, and the times the other followee's post Tweets, among other things.

Hope this helps; re-open the issue or write to me if you have more questions!

**Comment by Elmahedi** [comment]
> @harrymvr I can't run the script "train-teaching.py", because there isn't the file "twitter_data.dill". Can you provide me a sample data about the file "twitter_data.dill"?
> Thanks a lot!
Could you tell me please how did you manage with the issue
